title: "Brooklyn Fields"
email: i.am.the.brook@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio website created by Brooklyn Fields.
baseurl: "/" 
url: "https://brookthebook.github.io" 
twitter_username: BrooklynF333
github_username:  BrookTheBook

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
